@extends('admin.layouts.master')

@section('title')
{{ $user->company }}'s Profile
@endsection

@section('content')
<div class="row">
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">

		<h2>{{ $user->name }}</h2>

		<hr>

		<div class="row">
			<div class="col-md-4">
				<div class="card">
				  <ul class="list-group list-group-flush">
				    
				    <li class="list-group-item">
				    	<i class="far fa-building"></i>  {{ $user->company }}
					</li>

					<li class="list-group-item">
				    	<i class="fas fa-link"></i>  {{ $user->domain }}
					</li>

					<li class="list-group-item">
				    	<i class="fas fa-envelope"></i>  {{ $user->email }}
					</li>

					<li class="list-group-item">
				    	<i class="fas fa-phone"></i>  {{ $user->phone }}
					</li>

					<li class="list-group-item">
				    	<i class="fab fa-slack"></i>  {{ $user->slackURL }}
					</li>	

				  </ul>
				</div>
			</div>

			@if($user->webhook_url == '#')
				<div class="col-md-8">
					<div class="alert alert-info">
						<h3>No webhook on file.</h3>
						<p>This customer does not have a webhook on file for Slack billing notifications. Please assign one to alert them of bills.</p>

						<form action="/admin/webhook/save" method="post">

							@if ($errors->any())
							    <div class="alert alert-danger">
							        <ul>
							            @foreach ($errors->all() as $error)
							                <li>{{ $error }}</li>
							            @endforeach
							        </ul>
							    </div>
							@endif

							@csrf

							<input type="hidden" name="user" value="{{ $user->id }}">
							
							<div class="form-group">
								<label>Webhook URL</label>
							    <input type="url" class="form-control" name="webhook_url" aria-describedby="help" placeholder="https://hooks.slack.com/services/.../.../..........">
							    <small id="help" class="form-text text-muted">Please generate this through the Slack API portal.</small>
							</div>

							<div class="form-group">
								<button class="btn btn-lg btn-block btn-outline-info">Save</button>
							</div>

						</form>

					</div>
				</div>
			@else
				<div class="col-md-8">
                    <div class="alert alert-success">
                        <h3>Billing is all set!</h3>
                        <p>This customer has a webhook on file for Slack billing notifications. You can now bill them and have an alert show up in Slack. We reccomend sending this to the <code>#general</code> channel.</p>
                    </div>
                </div>
			@endif
		</div>

		<br>

		<div class="card">
		  <h5 class="card-header">Server(s)</h5>
		  <div class="card-body">

		    @if($user->servers->count() > 0)		    

			    @foreach($user->servers as $server)

			    	<div class="card">
					  <div class="card-header">
					    Server provider: <b>{{ strtoupper($server->server_provider) }}</b>
					  </div>
					  <div class="card-body">
					    <h5 class="card-title">Server information</h5>

					    <div class="form-group">
						    <label>Root password</label>
						    <input class="form-control" type="text" value="{{ $server->root_password }}" readonly>
					    </div>

					    <div class="form-group">
						    <label>Database password</label>
						    <input class="form-control" type="text" value="{{ $server->database_password }}" readonly>
					    </div>

					    <a href="/admin/delete/server/{{ $server->id }}" class="btn btn-danger">Delete Server</a>
					  </div>
					  <div class="card-footer text-muted">
					    Server Provisioned {{ $server->created_at->diffForHumans() }}
					  </div>
					</div>

					<br>

			    @endforeach

		    @else

			    <div class="alert alert-info">
			    	<b>{{ $user->company }}</b> has no servers, assign one now.
			    </div>

		    @endif

		    <hr>

		    <form action="/admin/new/server" method="POST">

			    	@csrf

			    	@if ($errors->any())
					    <br>
					    <div class="alert alert-danger">
					        <ul>
					            @foreach ($errors->all() as $error)
					                <li>{{ $error }}</li>
					            @endforeach
					        </ul>
					    </div>
					@endif

			    	<input type="hidden" name="user_id" value="{{ $user->id }}">
			    	
			    	<div class="form-group">
			    		<label>Server Provider</label>
			    		<select class="form-control" name="server_provider">
			    			<option></option>
			    			<option value="digitalocean">DigitalOcean</option>
					      	<option value="aws">AWS</option>
					      	<option value="vultr">Vultr</option>
					     	<option value="linode">Linode</option>
					    </select>
			    	</div>

			    	<div class="form-group">
						<label>Root password</label>
						<input name="root_password" type="password" class="form-control">
						<small class="form-text text-muted">This is generated by Laravel Forge for the <code>root</code> user.</small>
					</div>

					<div class="form-group">
						<label>Database password</label>
						<input name="database_password" type="password" class="form-control">
						<small class="form-text text-muted">This is generated by Laravel Forge for the <code>forge</code> user.</small>
					</div>

			    	<div class="form-group">
			    		<p>This server will be registered to <b>{{ $user->name }}</b> at <b>{{ $user->company }}</b></p>
			    	</div>

			    	<div class="form-group">
			    		<button type="submit" class="btn btn-block btn-lg btn-outline-primary">Register server</button>
			    	</div>

			    </form>

		  </div>
		</div>

		<br>

		<div class="card">
		  <h5 class="card-header">Charges</h5>
		  <div class="card-body">
              @if($user->jobs->count() > 0)
                  <table class="table table-bordered table-striped table-hover">

                      <thead class="thead-dark">
                          <th>Job ID</th>
                          <th>Description</th>
                          <th>Amount</th>
                          <th>Date Billed</th>
                      </thead>

                      @foreach($user->jobs as $job)
                          <tr>
                              <td><b>{{ $job->id }}</b></td>
                              <td>{{ $job->description }}</td>
                              <td>${{ number_format(($job->charge / 100), 2, '.', ',') }}</td>
                              <td>{{ $job->created_at->diffForHumans() }}</td>
                          </tr>
					@endforeach
				</table>

		    @else

			    <div class="alert alert-info">
			    	<b>{{ $user->company }}</b> has no jobs or bills.
			    </div>

		    @endif

		  </div>
		</div>

		<br>

        <br>

        <div class="card">
            <h5 class="card-header">Files</h5>
            <div class="card-body">
                @if($user->files->count() > 0)
                    <table class="table table-bordered table-striped table-hover">

                        <thead class="thead-dark">
                            <th>File ID</th>
                            <th>Filename</th>
                            <th>Owner</th>
                            <th>Shared</th>
                            <th>View</th>
                        </thead>

                        @foreach($user->files as $file)
                            <tr>
                                <td><b>{{ $file->id }}</b></td>
                                <td>{{ $file->description }}</td>
                                <td>{{ $file->user->name }}</td>
                                <td>{{ $file->created_at->diffForHumans() }}</td>
                                <td><a target="_blank" href="{{ route('admin.get.file', $file->id) }}" class="btn btn-block btn-outline-primary">View File</a></td>
                            </tr>
                        @endforeach
                    </table>

                @else

                    <div class="alert alert-info">
                        <b>{{ $user->company }}</b> has not shared any files with you.
                    </div>

                @endif

            </div>
        </div>

        <br>

	</main>
</div>
@endsection